name: AI Code Reviewer
description: Reviews pull requests using OpenAI

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests
      shell: bash

    - name: Run code review
      run: python code_review.py
      shell: bash
